export const PLACES = [
  {image: "", city: "Arlington Heights", searchTerm: "*Arlington*&location=*Heights*"},
  {image: "", city: "Aurora", searchTerm: "*Aurora*&location=*Il*"},
  {image: "https://idhh.dp.la/thumb/071ca0a36a5deb8d6be3a840c232b23e", city: "Canton", searchTerm: "*Canton*&location=*Il*"},
  {image: "", city: "Champaign", searchTerm: "*Champaign*"},
  {image: "", city: "Chicago", searchTerm: "*Chicago*"},
  {image: "", city: "Elgin", searchTerm: "*Elgin*"},
  {image: "", city: "Englewood", searchTerm: "*Englewood*&location=*Il*"},
  {image: "", city: "Highland Park", searchTerm: "*Highland*&location=*Park*"},
  {image: "", city: "Humboldt Park", searchTerm: "*Humboldt*&location=*Park*"},
  {image: "", city: "Huntley", searchTerm: "*Huntley*"},
  {image: "", city: "Joliet", searchTerm: "*Joliet*"},
  {image: "", city: "Lake View", searchTerm: '"Lake View (Chicago%2C Ill.)"'},
  {image: "", city: "Libertyville", searchTerm: "*Libertyville*"},
  {image: "", city: "Loop", searchTerm: "*Loop*&location=*Chicago*"},
  {image: "", city: "Mount Olive", searchTerm: "*Mount*&location=*Olive*"},
  {image: "", city: "Naperville", searchTerm: "*Naperville*"},
  {image: "", city: "Orland Park", searchTerm: "*Orland*&location=*Park*"},
  {image: "", city: "Park Ridge", searchTerm: "*Park*&location=*Ridge*"},
  {image: "", city: "Peoria", searchTerm: "*Peoria*"},
  {image: "", city: "Quincy", searchTerm: "*Quincy*&location=*Il*"},
  {image: "", city: "Rockford", searchTerm: "*Rockford*"},
  {image: "", city: "Skokie", searchTerm: "*Skokie*"},
  {image: "", city: "Springfield", searchTerm: "*Springfield*&location=*Il*"},
  {image: "", city: "Sterling", searchTerm: "*Sterling*"},
  {image: "", city: "West Town", searchTerm: '"West Town (Chicago%2C Ill.)"'}
];
